services:
  api:
    build:
      context: .
      dockerfile: api/Api/Dockerfile
    env_file:
      - api/Api/.env
    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 5
