services:
  api:
    build:
      context: .
      dockerfile: api/Api/Dockerfile
    depends_on:
      - redis
      - mongo
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 5

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 5

volumes:
  mongo-data:
