@Api_HostAddress = http://localhost:8080

POST {{Api_HostAddress}}/counter/increment
Accept: application/json

###

POST {{Api_HostAddress}}/counter/decrement
Accept: application/json

###

GET {{Api_HostAddress}}/counter

###

GET {{Api_HostAddress}}/features

###
